
# set GOOGLE_APPLICATION_CREDENTIALS=/home/syed/Downloads/mlops-471718-09aeb4bb6f16.json
google_credentials_path: '/home/syed/Downloads/mlops-471718-09aeb4bb6f16.json'

random_seed: 42

data_ingestion:
  bucket_name: 'mlops-project-1995-2'
  bucket_file_names: 
    - 'anime.csv'
    - 'anime_with_synopsis.csv'
    - 'animelist.csv'

model:
  embedding_size: 128
  loss: binary_crossentropy
  optimizer: Adam
  metrics: ["mse", "mae"]